import pytest

from commit_rules import SCISSORS, SUBJECT_HELP, check_message

GOOD_SUBJECT = "feat(M2): add chain validator"


@pytest.mark.parametrize(
    "message",
    [
        GOOD_SUBJECT,
        "fix(infra): pin checkout action\n\nLonger body text.\n",
        "docs(M10): record ADR-0007",
        f"{GOOD_SUBJECT}\n\nThe models are generated with datamodel-code-generator.",
        f"# Please enter the commit message\n{GOOD_SUBJECT}",
        "chore(M0): " + "x" * 71,
    ],
)
def test_acceptable_messages(message: str) -> None:
    assert check_message(message) == []


@pytest.mark.parametrize(
    "trailer",
    [
        "Co-Authored-By: Jane Doe <jane@example.com>",
        "co-authored-by: Pair Bot <bot@example.com>",
        "Generated with [SomeTool](https://example.com/tool)",
        "generated by a tool",
        "\U0001f916 Generated with SomeTool",
        "\U0001f916 made by a robot",
    ],
)
def test_attribution_is_rejected(trailer: str) -> None:
    errors = check_message(f"{GOOD_SUBJECT}\n\n{trailer}\n")
    assert any(e.startswith("forbidden attribution matched") for e in errors)
    assert SUBJECT_HELP not in errors


@pytest.mark.parametrize(
    "subject",
    [
        "Initial commit",
        "feat: no scope",
        "feat(M2):missing space",
        "feat(m2): lowercase milestone",
        "feat(core): scope must be a milestone or infra",
        "wip(M2): type not allowed",
        "feat(M2):  leading space in summary",
        "chore(M0): " + "x" * 72,
        "",
    ],
)
def test_bad_subject_is_rejected(subject: str) -> None:
    assert check_message(subject) == [SUBJECT_HELP]


def test_verbose_diff_below_scissors_is_ignored() -> None:
    message = f"{GOOD_SUBJECT}\n\n{SCISSORS}\nGenerated with a tool\nCo-authored-by: x <x@y.z>\n"
    assert check_message(message) == []
